openapi: 3.0.0
info:
  title: VL Learning Users API
  version: 1.0.0
  description: API that provides user operations for VL Learning
tags:
  - name: VL Learning Users API
    description: VL Learning Users API
paths:
  /api/v1/users:
    post:
      tags:
        - Users create post v1
      operationId: post-users-create
      summary: POST users create
      requestBody:
        description: New user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - type: object
          description: User
          properties:
            id:
              type: string
              description: User ID
          required:
            - id
    NewUser:
      allOf:
        - $ref: '#/components/schemas/UserCredentials'
        - type: object
          description: New user
          properties:
            externalId:
              type: string
              description: External ID
            name:
              type: string
              description: User name
          required:
            - externalId
            - name
    UserCredentials:
      type: object
      description: User
      properties:
        email:
          type: string
          description: Email
          format: email
        password:
          type: string
          description: Password
      required:
        - email
        - password
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string
        timestamp:
          type: integer
          format: int64
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorMessage'
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
        code:
          type: string