server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: listenings-route
          uri: ${VL_LEARNING_DOMAIN}
          predicates:
            - Path=/api/v1/listenings/**
          filters:
            - AuthenticationFilter
        - id: readings-route
          uri: ${VL_LEARNING_DOMAIN}
          predicates:
            - Path=/api/v1/readings/**
          filters:
            - AuthenticationFilter
        - id: descriptions-route
          uri: ${VL_LEARNING_DOMAIN}
          predicates:
            - Path=/api/v1/descriptions/**
          filters:
            - AuthenticationFilter
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true