server:
  port: 8082

services:
  users:
    base-url: http://localhost:8081

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: users-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: listenings-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/listenings/**
          filters:
            - AuthenticationFilter
        - id: descriptions-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/descriptions/**
          filters:
            - AuthenticationFilter
        - id: chats-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - AuthenticationFilter
        - id: descriptions-route
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/descriptions/**
          filters:
            - AuthenticationFilter
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true